# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160621_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='lift_type',
            field=models.CharField(choices=[('I have space', 'I have space'), ('I need a ride', 'I need a ride')], max_length=120),
        ),
    ]
