# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_notification',
            field=models.BooleanField(default=True),
        ),
    ]
